# First-Pass Batch 4

This notebook handles the deterministic first pass for batch 4 of 4. It does not retry failed rows.

## Drive And Repo Setup

Mount Drive, clone the repo into the runtime, and copy the required CSV inputs into the checkout.

- Reads: Google Drive, GitHub repo, runtime filesystem
- Writes: `/content/svg-kaggle-comptetition`, Drive output root
- Rerun-safe: Yes. It reclones the repo and recopies the inputs cleanly.

In [6]:
import os
import shutil
import subprocess
import sys
from pathlib import Path

from google.colab import drive

drive.mount("/content/drive")

GIT_REPO_URL = "https://github.com/Demetri65/svg-kaggle-competition.git"
CHECKOUT_PATH = Path("/content/svg-kaggle-comptetition")
DRIVE_ROOT = Path("/content/drive/MyDrive")
OUTPUT_ROOT = DRIVE_ROOT / "svg-kaggle-comptetition" / "submission_outputs"

if CHECKOUT_PATH.exists():
    shutil.rmtree(CHECKOUT_PATH)
subprocess.check_call(["git", "clone", GIT_REPO_URL, str(CHECKOUT_PATH)])

for required_name in ["test.csv", "train.csv", "sample_submission.csv"]:
    destination = CHECKOUT_PATH / required_name
    if destination.exists():
        continue

    preferred_sources = [
        DRIVE_ROOT / "svg-kaggle-comptetition" / required_name,
        DRIVE_ROOT / "Colab Notebooks" / "svg-kaggle-comptetition" / required_name,
    ]
    copied = False
    for candidate in preferred_sources:
        if candidate.exists():
            shutil.copy2(candidate, destination)
            copied = True
            break
    if not copied:
        for candidate in DRIVE_ROOT.rglob(required_name):
            if candidate.is_file():
                shutil.copy2(candidate, destination)
                copied = True
                break
    if not copied:
        raise FileNotFoundError(
            f"Could not find {required_name} in Google Drive. Copy it into {CHECKOUT_PATH} manually and rerun this cell."
        )

os.environ["SVG_KAGGLE_REPO_ROOT"] = str(CHECKOUT_PATH)
sys.path.insert(0, str(CHECKOUT_PATH))
OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)

print(f"Repo checkout: {CHECKOUT_PATH}")
print(f"Drive output root: {OUTPUT_ROOT}")

Mounted at /content/drive
Repo checkout: /content/svg-kaggle-comptetition
Drive output root: /content/drive/MyDrive/svg-kaggle-comptetition/submission_outputs

## Package Check

Install any missing runtime packages required by the shared helper module and this notebook.

- Reads: Current Python environment
- Writes: Installed runtime packages
- Rerun-safe: Yes. It only installs missing packages.

In [4]:
import importlib.util
import subprocess
import sys

REQUIRED_PACKAGES = {
    "pandas": "pandas",
    "numpy": "numpy",
    "torch": "torch",
    "transformers": "transformers",
    "peft": "peft",
    "accelerate": "accelerate",
    "cairosvg": "cairosvg",
    "skimage": "scikit-image",
    "PIL": "pillow",
}

missing_packages = [
    package_name
    for module_name, package_name in REQUIRED_PACKAGES.items()
    if importlib.util.find_spec(module_name) is None
]

if missing_packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", *missing_packages])
    print(f"Installed missing packages: {missing_packages}")
else:
    print("All required packages are already installed.")

All required packages are already installed.

## Load Helpers, Recommendation, And Batch Slice

Import the shared helper module, load the analysis recommendation, and select this notebook's fixed quarter of `test.csv`.

- Reads: Repo checkout, helper module, analysis recommendation, competition CSV files
- Writes: In-memory batch slice only
- Rerun-safe: Yes. It is deterministic because the batch boundaries are fixed.

In [7]:
import json
import os
from pathlib import Path

import pandas as pd
from IPython.display import SVG, Markdown, display

import submission_pipeline as pipeline

pipeline.set_global_seed(1337)
PATHS = pipeline.resolve_pipeline_paths(Path(os.environ["SVG_KAGGLE_REPO_ROOT"]), OUTPUT_ROOT)
CONFIG = pipeline.GenerationConfig(verbose_progress=True)
TEST_DF, SAMPLE_SUBMISSION_DF, TRAIN_DF = pipeline.load_competition_frames(PATHS)

print(f"Repo root: {PATHS.repo_root}")
print(f"Output root: {PATHS.output_root}")

BATCH_ID = 4
ANALYSIS_RECOMMENDATION = pipeline.load_analysis_recommendation(PATHS)
GENERATION_MODE = ANALYSIS_RECOMMENDATION.get("recommended_generation_mode", "body_only")
BATCH_DF = pipeline.select_batch_df(TEST_DF, batch_id=BATCH_ID, batch_count=4)
BATCH_DIR = pipeline.batch_output_dir(PATHS, BATCH_ID)
print(f"Recommended generation mode: {GENERATION_MODE}")
print(f"Batch rows: {len(BATCH_DF)}")
display(BATCH_DF[["id", "prompt", "row_index"]].head())

Repo root: /content/svg-kaggle-comptetition
Output root: /content/drive/MyDrive/svg-kaggle-comptetition/submission_outputs
Recommended generation mode: full_svg
Batch rows: 250

,id,prompt,row_index
0,66eec18f9c8a1b693aab52c1eb617116,The image shows a dark blue rectangular block ...,750
1,1746e618853fd17448f2740f90622e42,A slice of cheese with a rind is depicted in a...,751
2,af4a0c3d71c82e28ce9d41f9ee8c4c2d,The image contains a solid black color occupyi...,752
3,df01fd16ec344d444235519b71c8c738,An orange rectangular object with three horizo...,753
4,6cd2ff67e8c40d994115dc735aab04ab,A black speech bubble icon with two white hori...,754

## Load Model

Load the base model plus the LoRA adapter into the current Colab GPU runtime for first-pass generation.

- Reads: Base model on Hugging Face, LoRA adapter from repo
- Writes: In-memory model state only
- Rerun-safe: No. It is safe to rerun, but it reloads the model and costs time.

In [8]:
RUNTIME = pipeline.load_lora_runtime(PATHS.adapter_dir)
print(f"Loaded runtime on: {RUNTIME.runtime_device}")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Loaded runtime on: cuda

## Deterministic First Pass

Run one deterministic generation attempt per row in this batch and save the success/failure artifacts for the merge notebook.

- Reads: Selected batch rows, model runtime
- Writes: Batch output CSV artifacts under this batch directory
- Rerun-safe: Yes. It recomputes and overwrites this batch's artifacts.

In [9]:
FIRST_PASS_RESULTS_DF = pipeline.run_first_pass_batch(
    BATCH_DF,
    RUNTIME,
    batch_id=BATCH_ID,
    generation_mode=GENERATION_MODE,
    config=CONFIG,
)
pipeline.save_batch_outputs(FIRST_PASS_RESULTS_DF, BATCH_DIR)
print(f"Wrote batch artifacts to: {BATCH_DIR}")

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[batch_4 1/250] row 66eec18f9c8a1b693aab52c1eb617116: attempt 1/1 (deterministic)
[batch_4 1/250] row 66eec18f9c8a1b693aab52c1eb617116: success on attempt 1/1
[batch_4 2/250] row 1746e618853fd17448f2740f90622e42: attempt 1/1 (deterministic)
[batch_4 2/250] row 1746e618853fd17448f2740f90622e42: attempt 1/1 failed: unclosed token: line 3, column 0
[batch_4 3/250] row af4a0c3d71c82e28ce9d41f9ee8c4c2d: attempt 1/1 (deterministic)
[batch_4 3/250] row af4a0c3d71c82e28ce9d41f9ee8c4c2d: success on attempt 1/1
[batch_4 4/250] row df01fd16ec344d444235519b71c8c738: attempt 1/1 (deterministic)
[batch_4 4/250] row df01fd16ec344d444235519b71c8c738: success on attempt 1/1
[batch_4 5/250] row 6cd2ff67e8c40d994115dc735aab04ab: attempt 1/1 (deterministic)
[batch_4 5/250] row 6cd2ff67e8c40d994115dc735aab04ab: success on attempt 1/1
[batch_4 6/250] row 9ad34e074349bc67029395238ce85ab5: attempt 1/1 (deterministic)
[batch_4 6/250] row 9ad34e074349bc67029395238ce85ab5: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 7/250] row 46a4faf1ae6a4426e6e96a35abb5074f: attempt 1/1 (deterministic)
[batch_4 7/250] row 46a4faf1ae6a4426e6e96a35abb5074f: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 8/250] row 11c1b206357e957e417b6fb820eb7ad0: attempt 1/1 (deterministic)
[batch_4 8/250] row 11c1b206357e957e417b6fb820eb7ad0: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 9/250] row b49e57348a42e770f507d12b21652c1f: attempt 1/1 (deterministic)
[batch_4 9/250] row b49e57348a42e770f507d12b21652c1f: attempt 1/1 failed: unclosed token: line 5, column 0
[batch_4 10/250] row 9872f10883b923d198db1dc9bc62d15a: attempt 1/1 (deterministic)
[batch_4 10/250] row 9872f10883b923d198db1dc9bc62d15a: success on attempt 1/1
[batch_4 11/250] row ede87c9406eefbb3f9a689b9f30201c6: attempt 1/1 (deterministic)
[batch_4 11/250] row ede87c9406eefbb3f9a689b9f30201c6: attempt 1/1 failed: unclosed token: line 3, column 0
[batch_4 12/250] row 5839a574d74b7f3cc7a7c48528f3cf2f: attempt 1/1 (deterministic)
[batch_4 12/250] row 5839a574d74b7f3cc7a7c48528f3cf2f: success on attempt 1/1
[batch_4 13/250] row 8b55d958-cd2e-4e51-a940-beea6b96e718: attempt 1/1 (deterministic)
[batch_4 13/250] row 8b55d958-cd2e-4e51-a940-beea6b96e718: success on attempt 1/1
[batch_4 14/250] row 388ccc7936d31aaba4cecbff344ceb78: attempt 1/1 (deterministic)
[batch_4 14/250] row 388ccc7936d31aaba4cecbff344ceb78: success on attempt 1/1
[batch_4 15/250] row 4e8dcd0d52b5e39bb8b0a63594d25e50: attempt 1/1 (deterministic)
[batch_4 15/250] row 4e8dcd0d52b5e39bb8b0a63594d25e50: success on attempt 1/1
[batch_4 16/250] row 2e44a78926bf2e58f9839493a4fb9a3a: attempt 1/1 (deterministic)
[batch_4 16/250] row 2e44a78926bf2e58f9839493a4fb9a3a: success on attempt 1/1
[batch_4 17/250] row ca2d3a6439b3cea6f1c633f719b13189: attempt 1/1 (deterministic)
[batch_4 17/250] row ca2d3a6439b3cea6f1c633f719b13189: success on attempt 1/1
[batch_4 18/250] row 0a91f876f6c2294c12c2213f23830a4f: attempt 1/1 (deterministic)
[batch_4 18/250] row 0a91f876f6c2294c12c2213f23830a4f: attempt 1/1 failed: unclosed token: line 5, column 0
[batch_4 19/250] row fa5c275c8505741224c926183f9170d7: attempt 1/1 (deterministic)
[batch_4 19/250] row fa5c275c8505741224c926183f9170d7: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 20/250] row d3dd2646d2862a60cedd6f8ce7112a34: attempt 1/1 (deterministic)
[batch_4 20/250] row d3dd2646d2862a60cedd6f8ce7112a34: attempt 1/1 failed: unclosed token: line 9, column 0
[batch_4 21/250] row 2e6d4bee953ce3099164392bbf49529e: attempt 1/1 (deterministic)
[batch_4 21/250] row 2e6d4bee953ce3099164392bbf49529e: success on attempt 1/1
[batch_4 22/250] row 65ca56724f8e271537ee048c58f5fc66: attempt 1/1 (deterministic)
[batch_4 22/250] row 65ca56724f8e271537ee048c58f5fc66: success on attempt 1/1
[batch_4 23/250] row 4f0f1ca31425d5e73907dd50ad5ea209: attempt 1/1 (deterministic)
[batch_4 23/250] row 4f0f1ca31425d5e73907dd50ad5ea209: attempt 1/1 failed: unclosed token: line 16, column 4
[batch_4 24/250] row 291895a6f3bc0900648190cdfd70ffd6: attempt 1/1 (deterministic)
[batch_4 24/250] row 291895a6f3bc0900648190cdfd70ffd6: success on attempt 1/1
[batch_4 25/250] row 8b78ab189bc74d57e94affa65ed64547: attempt 1/1 (deterministic)
[batch_4 25/250] row 8b78ab189bc74d57e94affa65ed64547: attempt 1/1 failed: unclosed token: line 20, column 0
[batch_4 26/250] row 7f5c6d9dd30f78f550c707acc5c17689: attempt 1/1 (deterministic)
[batch_4 26/250] row 7f5c6d9dd30f78f550c707acc5c17689: success on attempt 1/1
[batch_4 27/250] row d217ec5e54247f554658c0b55c0f7b88: attempt 1/1 (deterministic)
[batch_4 27/250] row d217ec5e54247f554658c0b55c0f7b88: success on attempt 1/1
[batch_4 28/250] row 3b35b6161536c913c2e925688e6e1909: attempt 1/1 (deterministic)
[batch_4 28/250] row 3b35b6161536c913c2e925688e6e1909: attempt 1/1 failed: unclosed token: line 22, column 0
[batch_4 29/250] row 4b50219c5f811a4a2246f70fc8778fb7: attempt 1/1 (deterministic)
[batch_4 29/250] row 4b50219c5f811a4a2246f70fc8778fb7: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 30/250] row 7b26043f0d13cda39371e4b339ebadf7: attempt 1/1 (deterministic)
[batch_4 30/250] row 7b26043f0d13cda39371e4b339ebadf7: attempt 1/1 failed: unclosed token: line 7, column 0
[batch_4 31/250] row f7e100176f3abaa371f2be1f2591b052: attempt 1/1 (deterministic)
[batch_4 31/250] row f7e100176f3abaa371f2be1f2591b052: success on attempt 1/1
[batch_4 32/250] row 7be87f50d6ce946ddf06aa2699e8fc7d: attempt 1/1 (deterministic)
[batch_4 32/250] row 7be87f50d6ce946ddf06aa2699e8fc7d: attempt 1/1 failed: unclosed token: line 3, column 0
[batch_4 33/250] row 2179a3741a0ab1aa7c2d4662936b290c: attempt 1/1 (deterministic)
[batch_4 33/250] row 2179a3741a0ab1aa7c2d4662936b290c: success on attempt 1/1
[batch_4 34/250] row ad497666ac65587fce985d7623871ae7: attempt 1/1 (deterministic)
[batch_4 34/250] row ad497666ac65587fce985d7623871ae7: attempt 1/1 failed: unclosed token: line 11, column 0
[batch_4 35/250] row d0316313-c830-4f01-9e3c-75e383512aa8: attempt 1/1 (deterministic)
[batch_4 35/250] row d0316313-c830-4f01-9e3c-75e383512aa8: success on attempt 1/1
[batch_4 36/250] row bef3b5702afe02ec752caa10c598f0fb: attempt 1/1 (deterministic)
[batch_4 36/250] row bef3b5702afe02ec752caa10c598f0fb: success on attempt 1/1
[batch_4 37/250] row 59433b6bf3dc2b8185aad87ff88b37e9: attempt 1/1 (deterministic)
[batch_4 37/250] row 59433b6bf3dc2b8185aad87ff88b37e9: success on attempt 1/1
[batch_4 38/250] row cccde842a9770067e91c4fe35cb36e05: attempt 1/1 (deterministic)
[batch_4 38/250] row cccde842a9770067e91c4fe35cb36e05: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 39/250] row 8d9a73f5da5369b5ee2483cb71f2a498: attempt 1/1 (deterministic)
[batch_4 39/250] row 8d9a73f5da5369b5ee2483cb71f2a498: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 40/250] row 60782d20cc8bfb457db8081589abf190: attempt 1/1 (deterministic)
[batch_4 40/250] row 60782d20cc8bfb457db8081589abf190: attempt 1/1 failed: unclosed token: line 17, column 2
[batch_4 41/250] row 7884ebaf59a1407a0d842e8fedb04ac6: attempt 1/1 (deterministic)
[batch_4 41/250] row 7884ebaf59a1407a0d842e8fedb04ac6: success on attempt 1/1
[batch_4 42/250] row 52b768babdfab2dde3b7f5754ab0356d: attempt 1/1 (deterministic)
[batch_4 42/250] row 52b768babdfab2dde3b7f5754ab0356d: attempt 1/1 failed: unclosed token: line 11, column 0
[batch_4 43/250] row c06c776d341830fe0656ce80a4837c43: attempt 1/1 (deterministic)
[batch_4 43/250] row c06c776d341830fe0656ce80a4837c43: attempt 1/1 failed: unclosed token: line 8, column 0
[batch_4 44/250] row 69f9025a676799aa7c78d9391f364e42: attempt 1/1 (deterministic)
[batch_4 44/250] row 69f9025a676799aa7c78d9391f364e42: attempt 1/1 failed: unclosed token: line 9, column 0
[batch_4 45/250] row b4055e74149d72b39af4bb6ed912d4dd: attempt 1/1 (deterministic)
[batch_4 45/250] row b4055e74149d72b39af4bb6ed912d4dd: success on attempt 1/1
[batch_4 46/250] row 0ab856c569e714140199edcea3bf4b1b: attempt 1/1 (deterministic)
[batch_4 46/250] row 0ab856c569e714140199edcea3bf4b1b: success on attempt 1/1
[batch_4 47/250] row 7a48e2e3e1cfc84084ee88f328768326: attempt 1/1 (deterministic)
[batch_4 47/250] row 7a48e2e3e1cfc84084ee88f328768326: success on attempt 1/1
[batch_4 48/250] row 9c33cfa86000008f09d0d07bc3a8867e: attempt 1/1 (deterministic)
[batch_4 48/250] row 9c33cfa86000008f09d0d07bc3a8867e: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 49/250] row 36a35cdca1a41057186eae176e77f782: attempt 1/1 (deterministic)
[batch_4 49/250] row 36a35cdca1a41057186eae176e77f782: success on attempt 1/1
[batch_4 50/250] row ecccb36d-f9f3-405b-aec4-692a0b41c947: attempt 1/1 (deterministic)
[batch_4 50/250] row ecccb36d-f9f3-405b-aec4-692a0b41c947: success on attempt 1/1
[batch_4 51/250] row 2fe46e535a6daafd0ccf76ff1632c924: attempt 1/1 (deterministic)
[batch_4 51/250] row 2fe46e535a6daafd0ccf76ff1632c924: attempt 1/1 failed: unclosed token: line 3, column 0
[batch_4 52/250] row e2f14b4772c54eab79d94ddd1086d4a8: attempt 1/1 (deterministic)
[batch_4 52/250] row e2f14b4772c54eab79d94ddd1086d4a8: success on attempt 1/1
[batch_4 53/250] row c77bfcff2ef267f1687ee338811418a7: attempt 1/1 (deterministic)
[batch_4 53/250] row c77bfcff2ef267f1687ee338811418a7: success on attempt 1/1
[batch_4 54/250] row 11de9db4bf6f7c89ccef2e8f5255f940: attempt 1/1 (deterministic)
[batch_4 54/250] row 11de9db4bf6f7c89ccef2e8f5255f940: attempt 1/1 failed: unclosed token: line 11, column 0
[batch_4 55/250] row 31007fcfb3d29b96482936fef1627474: attempt 1/1 (deterministic)
[batch_4 55/250] row 31007fcfb3d29b96482936fef1627474: success on attempt 1/1
[batch_4 56/250] row aced284fc4b70f07ffb942630def4b70: attempt 1/1 (deterministic)
[batch_4 56/250] row aced284fc4b70f07ffb942630def4b70: success on attempt 1/1
[batch_4 57/250] row 71c80fc88d513e986ada1a2c216f27fa: attempt 1/1 (deterministic)
[batch_4 57/250] row 71c80fc88d513e986ada1a2c216f27fa: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 58/250] row 2416e0ec038a44a6796b03e1ca47e793: attempt 1/1 (deterministic)
[batch_4 58/250] row 2416e0ec038a44a6796b03e1ca47e793: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 59/250] row 651d77d6513bb3bc5015b268b2478288: attempt 1/1 (deterministic)
[batch_4 59/250] row 651d77d6513bb3bc5015b268b2478288: success on attempt 1/1
[batch_4 60/250] row 4c7f68ff837be67b255daa570abe07fb: attempt 1/1 (deterministic)
[batch_4 60/250] row 4c7f68ff837be67b255daa570abe07fb: attempt 1/1 failed: unclosed token: line 11, column 0
[batch_4 61/250] row bfea09a06494a8d5c375a442159b9711: attempt 1/1 (deterministic)
[batch_4 61/250] row bfea09a06494a8d5c375a442159b9711: success on attempt 1/1
[batch_4 62/250] row 9a44d8309fefe366bdfcf6dfe228d580: attempt 1/1 (deterministic)
[batch_4 62/250] row 9a44d8309fefe366bdfcf6dfe228d580: success on attempt 1/1
[batch_4 63/250] row e86ce2a192773fe0c96294a8e10623c4: attempt 1/1 (deterministic)
[batch_4 63/250] row e86ce2a192773fe0c96294a8e10623c4: attempt 1/1 failed: unclosed token: line 15, column 0
[batch_4 64/250] row f306de31c0bd997ca6d12994325dd787: attempt 1/1 (deterministic)
[batch_4 64/250] row f306de31c0bd997ca6d12994325dd787: attempt 1/1 failed: unclosed token: line 8, column 0
[batch_4 65/250] row e77f70272bee4c42cfa1e4764dde6c86: attempt 1/1 (deterministic)
[batch_4 65/250] row e77f70272bee4c42cfa1e4764dde6c86: success on attempt 1/1
[batch_4 66/250] row 4e7b4e261c3e2bd62b06b2ac9aa91aa1: attempt 1/1 (deterministic)
[batch_4 66/250] row 4e7b4e261c3e2bd62b06b2ac9aa91aa1: success on attempt 1/1
[batch_4 67/250] row ddad0ee9440251e63a9cec90b10d6ec6: attempt 1/1 (deterministic)
[batch_4 67/250] row ddad0ee9440251e63a9cec90b10d6ec6: attempt 1/1 failed: unclosed token: line 5, column 0
[batch_4 68/250] row b7c33256-268d-48b6-8e2e-3a1342b81df1: attempt 1/1 (deterministic)
[batch_4 68/250] row b7c33256-268d-48b6-8e2e-3a1342b81df1: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 69/250] row 2431467e520986551714b65e3ab50e3b: attempt 1/1 (deterministic)
[batch_4 69/250] row 2431467e520986551714b65e3ab50e3b: success on attempt 1/1
[batch_4 70/250] row 4186c0e597bd570c83b7b206d4115e16: attempt 1/1 (deterministic)
[batch_4 70/250] row 4186c0e597bd570c83b7b206d4115e16: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 71/250] row 22ccf1fe0913a4ba90e8fe9f959512bc: attempt 1/1 (deterministic)
[batch_4 71/250] row 22ccf1fe0913a4ba90e8fe9f959512bc: attempt 1/1 failed: unclosed token: line 9, column 0
[batch_4 72/250] row 9ef67cc04c109544fd8ca5096e5f56d7: attempt 1/1 (deterministic)
[batch_4 72/250] row 9ef67cc04c109544fd8ca5096e5f56d7: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 73/250] row c0b082b5-a6d8-4b0f-98f2-d4856daffb78: attempt 1/1 (deterministic)
[batch_4 73/250] row c0b082b5-a6d8-4b0f-98f2-d4856daffb78: attempt 1/1 failed: unclosed token: line 10, column 0
[batch_4 74/250] row 6a10a30f5106b16c5a03380efb724236: attempt 1/1 (deterministic)
[batch_4 74/250] row 6a10a30f5106b16c5a03380efb724236: attempt 1/1 failed: unclosed token: line 12, column 0
[batch_4 75/250] row e3ff37b0428b939fe5e6d2206eb44c50: attempt 1/1 (deterministic)
[batch_4 75/250] row e3ff37b0428b939fe5e6d2206eb44c50: success on attempt 1/1
[batch_4 76/250] row 3e5e60d596b309856a54fb4a70f7d0fb: attempt 1/1 (deterministic)
[batch_4 76/250] row 3e5e60d596b309856a54fb4a70f7d0fb: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 77/250] row 281f7a7bbedcc3dabe56c34309ce0bf7: attempt 1/1 (deterministic)
[batch_4 77/250] row 281f7a7bbedcc3dabe56c34309ce0bf7: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 78/250] row d85928edea1d03e330c870425e4ca375: attempt 1/1 (deterministic)
[batch_4 78/250] row d85928edea1d03e330c870425e4ca375: success on attempt 1/1
[batch_4 79/250] row 3f93cf9a13f935ddbe2ca7a3a4ecaf44: attempt 1/1 (deterministic)
[batch_4 79/250] row 3f93cf9a13f935ddbe2ca7a3a4ecaf44: success on attempt 1/1
[batch_4 80/250] row 7b4a2d22-bc7e-4231-b39c-2c9c075d0d99: attempt 1/1 (deterministic)
[batch_4 80/250] row 7b4a2d22-bc7e-4231-b39c-2c9c075d0d99: attempt 1/1 failed: unclosed token: line 22, column 0
[batch_4 81/250] row d708199af57645920649bf70701ad00b: attempt 1/1 (deterministic)
[batch_4 81/250] row d708199af57645920649bf70701ad00b: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 82/250] row 3882854a55bd3395269935f3dfaf0e04: attempt 1/1 (deterministic)
[batch_4 82/250] row 3882854a55bd3395269935f3dfaf0e04: success on attempt 1/1
[batch_4 83/250] row 73dc2a469ca2158870c301e1659e5cb3: attempt 1/1 (deterministic)
[batch_4 83/250] row 73dc2a469ca2158870c301e1659e5cb3: attempt 1/1 failed: unclosed token: line 21, column 0
[batch_4 84/250] row 20d463daeb37810f910859c9e80bea4f: attempt 1/1 (deterministic)
[batch_4 84/250] row 20d463daeb37810f910859c9e80bea4f: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 85/250] row 55b63de07f0b268ffa77a8b03658e48a: attempt 1/1 (deterministic)
[batch_4 85/250] row 55b63de07f0b268ffa77a8b03658e48a: success on attempt 1/1
[batch_4 86/250] row 8bdc76a8-fe3c-44a4-a364-86fb8a7b30f9: attempt 1/1 (deterministic)
[batch_4 86/250] row 8bdc76a8-fe3c-44a4-a364-86fb8a7b30f9: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 87/250] row 6b65f7999301cb59cbf91807f8e0e3df: attempt 1/1 (deterministic)
[batch_4 87/250] row 6b65f7999301cb59cbf91807f8e0e3df: attempt 1/1 failed: unclosed token: line 24, column 0
[batch_4 88/250] row d755512b6a9f00a406ea8e3f270d047c: attempt 1/1 (deterministic)
[batch_4 88/250] row d755512b6a9f00a406ea8e3f270d047c: attempt 1/1 failed: unclosed token: line 11, column 0
[batch_4 89/250] row ff4c2cae6fe0ac0bb40cb56c5d95b871: attempt 1/1 (deterministic)
[batch_4 89/250] row ff4c2cae6fe0ac0bb40cb56c5d95b871: attempt 1/1 failed: unclosed token: line 18, column 0
[batch_4 90/250] row 54f48ef9b405c33b8169c8a91d06aed8: attempt 1/1 (deterministic)
[batch_4 90/250] row 54f48ef9b405c33b8169c8a91d06aed8: success on attempt 1/1
[batch_4 91/250] row thesantatitan_deepseek-svg-dataset_0001383: attempt 1/1 (deterministic)
[batch_4 91/250] row thesantatitan_deepseek-svg-dataset_0001383: success on attempt 1/1
[batch_4 92/250] row 259272d045228e1454dc73f20e4b21fe: attempt 1/1 (deterministic)
[batch_4 92/250] row 259272d045228e1454dc73f20e4b21fe: success on attempt 1/1
[batch_4 93/250] row 92d0bad60d4a2ea751692cd033980c49: attempt 1/1 (deterministic)
[batch_4 93/250] row 92d0bad60d4a2ea751692cd033980c49: attempt 1/1 failed: unclosed token: line 2, column 0
[batch_4 94/250] row 8eedb7c0c6e1a7dc6478a6d5bfcf13cc: attempt 1/1 (deterministic)
[batch_4 94/250] row 8eedb7c0c6e1a7dc6478a6d5bfcf13cc: attempt 1/1 failed: unclosed token: line 5, column 0
[batch_4 95/250] row 69cf47984e44a1538e7d353b34def42f: attempt 1/1 (deterministic)
[batch_4 95/250] row 69cf47984e44a1538e7d353b34def42f: attempt 1/1 failed: unclosed token: line 5, column 0
[batch_4 96/250] row 75b079b90cfa4c4e4b4bcbae5658c3b5: attempt 1/1 (deterministic)
[batch_4 96/250] row 75b079b90cfa4c4e4b4bcbae5658c3b5: attempt 1/1 failed: unclosed token: line 12, column 2
[batch_4 97/250] row 487c4e7bd1e2ee065733d2f80e94efec: attempt 1/1 (deterministic)
[batch_4 97/250] row 487c4e7bd1e2ee065733d2f80e94efec: attempt 1/1 failed: unclosed token: line 6, column 0
[batch_4 98/250] row dbc4ea2e435a7bb740ac91585d351f12: attempt 1/1 (deterministic)
[batch_4 98/250] row dbc4ea2e435a7bb740ac91585d351f12: success on attempt 1/1
[batch_4 99/250] row thesantatitan_deepseek-svg-dataset_0000091: attempt 1/1 (deterministic)
[batch_4 99/250] row thesantatitan_deepseek-svg-dataset_0000091: success on attempt 1/1
[batch_4 100/250] row 3e5411b8d69c89782f4bed8961cff046: attempt 1/1 (deterministic)
[batch_4 100/250] row 3e5411b8d69c89782f4bed8961cff046: attempt 1/1 failed: no element found: line 13, column 65
[batch_4 101/250] row c71073a4a5707759d10e007d44fc4387: attempt 1/1 (deterministic)
[batch_4 101/250] row c71073a4a5707759d10e007d44fc4387: success on attempt 1/1
[batch_4 102/250] row 9971eab5-4b43-44ec-a24c-b2719d0b8748: attempt 1/1 (deterministic)
[batch_4 102/250] row 9971eab5-4b43-44ec-a24c-b2719d0b8748: attempt 1/1 failed: unclosed token: line 8, column 0
[batch_4 103/250] row 1fc843fe63b2d9171fc37633e1e1e472: attempt 1/1 (deterministic)
[batch_4 103/250] row 1fc843fe63b2d9171fc37633e1e1e472: success on attempt 1/1
[batch_4 104/250] row c77776e9794164682f323900334bba75: attempt 1/1 (deterministic)
[batch_4 104/250] row c77776e9794164682f323900334bba75: success on attempt 1/1
[batch_4 105/250] row 849b07a02221722a6cd198a1e4c068a6: attempt 1/1 (deterministic)
[batch_4 105/250] row 849b07a02221722a6cd198a1e4c068a6: success on attempt 1/1
[batch_4 106/250] row 27f009c6aa33171f66c64a2de29a74bf: attempt 1/1 (deterministic)
[batch_4 106/250] row 27f009c6aa33171f66c64a2de29a74bf: success on attempt 1/1
[batch_4 107/250] row 1bf29e037aafe2ae08195dbdbf2faf76: attempt 1/1 (deterministic)
[batch_4 107/250] row 1bf29e037aafe2ae08195dbdbf2faf76: success on attempt 1/1
[batch_4 108/250] row cc1cd78fa1802e71cb180157748d7a21: attempt 1/1 (deterministic)
[batch_4 108/250] row cc1cd78fa1802e71cb180157748d7a21: attempt 1/1 failed: unclosed token: line 17, column 2
[batch_4 109/250] row aa72b958784d741e2f739f3de8cd87ec: attempt 1/1 (deterministic)
[batch_4 109/250] row aa72b958784d741e2f739f3de8cd87ec: success on attempt 1/1
[batch_4 110/250] row e8da5391556ebf803535dd7b25f4e664: attempt 1/1 (deterministic)
[batch_4 110/250] row e8da5391556ebf803535dd7b25f4e664: success on attempt 1/1
[batch_4 111/250] row 65a8cc311b2f6a8372023c24a19e2a98: attempt 1/1 (deterministic)
[batch_4 111/250] row 65a8cc311b2f6a8372023c24a19e2a98: attempt 1/1 failed: unclosed token: line 3, column 0
[batch_4 112/250] row 4b184fd59f863d57f3b442899fd44ad3: attempt 1/1 (deterministic)
[batch_4 112/250] row 4b184fd59f863d57f3b442899fd44ad3: attempt 1/1 failed: unclosed token: line 11, column 0
[batch_4 113/250] row fb0d5ee90f5bbf7c8d887e8126e2e196: attempt 1/1 (deterministic)

## Batch Summary

Show the first-pass success/failure totals and inspect a few failed rows with their gate errors.

- Reads: Batch result artifacts in memory
- Writes: Nothing
- Rerun-safe: Yes. Read-only display cell.

In [10]:
display(pipeline.summarize_batch_results(FIRST_PASS_RESULTS_DF))
FAILED_DF = FIRST_PASS_RESULTS_DF[~FIRST_PASS_RESULTS_DF["first_pass_success"]].copy()
if FAILED_DF.empty:
    print("No failed rows in this batch.")
else:
    display(FAILED_DF[["id", "row_index", "generation_mode", "gate_error"]].head(20))

                    metric       value
0                     rows  250.000000
1     first_pass_successes  120.000000
2      first_pass_failures  130.000000
3     mean_runtime_seconds   14.696688
4  mean_char_len_successes  350.075000

,id,row_index,generation_mode,gate_error
1,1746e618853fd17448f2740f90622e42,751,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
5,9ad34e074349bc67029395238ce85ab5,755,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
6,46a4faf1ae6a4426e6e96a35abb5074f,756,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
7,11c1b206357e957e417b6fb820eb7ad0,757,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
8,b49e57348a42e770f507d12b21652c1f,758,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
10,ede87c9406eefbb3f9a689b9f30201c6,760,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
17,0a91f876f6c2294c12c2213f23830a4f,767,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
18,fa5c275c8505741224c926183f9170d7,768,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
19,d3dd2646d2862a60cedd6f8ce7112a34,769,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
22,4f0f1ca31425d5e73907dd50ad5ea209,772,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
24,8b78ab189bc74d57e94affa65ed64547,774,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
27,3b35b6161536c913c2e925688e6e1909,777,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
28,4b50219c5f811a4a2246f70fc8778fb7,778,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
29,7b26043f0d13cda39371e4b339ebadf7,779,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
31,7be87f50d6ce946ddf06aa2699e8fc7d,781,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
33,ad497666ac65587fce985d7623871ae7,783,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
37,cccde842a9770067e91c4fe35cb36e05,787,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
38,8d9a73f5da5369b5ee2483cb71f2a498,788,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
39,60782d20cc8bfb457db8081589abf190,789,full_svg,Failed after 1 attempts. attempt 1: unclosed t...
41,52b768babdfab2dde3b7f5754ab0356d,791,full_svg,Failed after 1 attempts. attempt 1: unclosed t...